version: '3.8'
services:
  aws:
    image: 'localstack/localstack'
    container_name: 'localstack'
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=qwer
      - AWS_SECRET_ACCESS_KEY=1234
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - '4566:4566'
  kcdapp1:
    image: kcdapp1
    command: python3 main.py
    ports:
      - "8000:8000"
    depends_on:
      - aws
